Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'CodeQ.AdvancedPublish':
            resource: resource://CodeQ.AdvancedPublish/Public/NeosUserInterface/Plugin.js

      frontendConfiguration:
        'CodeQ.AdvancedPublish':
          iframeUri: '/neos/advancedpublish/new?inEmbedMode=true'
