Neos:
  Neos:
    modules:
      management:
        submodules:
          publications:
            label: 'Veröffentlichungen'
            controller: 'CodeQ\AdvancedPublish\Controller\PublicationBackendModuleController'
            description: 'i18n'
            icon: 'icon-star'
            mainStylesheet: 'Lite'
            additionalResources:
              styleSheets:
                - 'resource://CodeQ.AdvancedPublish/Public/Styles/Index.css'
              javaScripts:
                - 'resource://CodeQ.AdvancedPublish/Public/JavaScript/Index.js'
  Flow:
    mvc:
      routes:
        'CodeQ.AdvancedPublish': true
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'CodeQ.AdvancedPublish:Controllers':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'CodeQ\AdvancedPublish\Controller\.*'
