Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'CodeQ.AdvancedPublish':
            resource: resource://CodeQ.AdvancedPublish/Public/NeosUserInterface/Plugin.js

      frontendConfiguration:
        'CodeQ.AdvancedPublish':
          iframeUri: '/neos/management/publications?moduleArguments%5B%40package%5D=codeq.advancedpublish&moduleArguments%5B%40controller%5D=publicationbackendmodule&moduleArguments%5B%40action%5D=new&moduleArguments%5B%40format%5D=html&moduleArguments%5B%40subpackage%5D='
